# Change these first
owner: Xicrosoft # Your GitHub organization or username, where this repository lives
repo: e5-uptime # The name of this repository

sites:
  - name: Renew X 1
    url: https://e5-1.xicro.pp.ua
  - name: Renew X 2
    url: https://e5-2.xicro.pp.ua
  - name: Renew X 3
    url: https://e5-3.xicro.pp.ua


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: e5-status.xicro.pp.ua
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Renew X Shared Admin Upptime"
  introTitle: "此页面用于监控共享 E5 Renew X Admin 服务的状态"
  # introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: About Me
      href: https://linktr.ee/Xicrosoft

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
